# Generated by Django 5.0.2 on 2024-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('bpm', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
