# Generated by Django 5.0.2 on 2024-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='bpm',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
