# Generated by Django 5.0.2 on 2024-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_beat_audio_alter_beat_bpm_alter_beat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/audio'),
        ),
    ]
