# Generated by Django 5.0.6 on 2024-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_beat_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
