# Generated by Django 5.0.6 on 2024-10-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_beat_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='key',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
